name: pristine-homebrew

description: Setup pristine Homebrew and cache it

inputs:
  os:
    description: Runner OS (used in the cache key)
    required: true
  restore:
    description: Restore a cached pristine Homebrew
    required: false
    default: "true"

env:
  CACHE_PATHS:

runs:
  using: composite
  steps:
    - name: Cache lookup
      id: cache_lookup
      uses: actions/cache/restore@v4
      with:
        lookup-only: true
        path: /tmp/hoge
        key: brew-pristine-${{ inputs.os }}-${{ github.ref_name }}-${{ steps.brew.outputs.version }}-hoge
    - if: steps.restore.outputs.cache-hit != 'true'
      name: prepare
      run: |
        mkdir /tmp/hoge
        echo cache_test > /tmp/hoge/test.txt
    - name: Restore pristine Homebrew
      id: cache_restore
      if: inputs.restore == 'true' && steps.cache_lookup.outputs.cache-hit == 'true'
      uses: actions/cache/restore@v4
      with:
        path: /tmp/hoge
        key: brew-pristine-${{ inputs.os }}-${{ github.ref_name }}-${{ steps.brew.outputs.version }}-hoge
    - name: Save pristine Homebrew
      if: steps.cache_lookup.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: /tmp/hoge
        key: brew-pristine-${{ inputs.os }}-${{ github.ref_name }}-${{ steps.brew.outputs.version }}-hoge
