name: pristine-homebrew

description: Setup pristine Homebrew and cache it

inputs:
  os:
    description: Runner OS (used in the cache key)
    required: true
  restore:
    description: Restore a cached pristine Homebrew
    required: false
    default: "true"

env:
  CACHE_PATHS:

runs:
  using: composite
  steps:
    - name: Cache lookup
      id: cache_lookup
      uses: actions/cache/restore@v4
      with:
        lookup-only: true
        path: |
          /opt/homebrew/bin
          /opt/homebrew/etc
        key: brew-pristine-${{ inputs.os }}-${{ github.ref_name }}-${{ steps.brew.outputs.version }}-test-multi2
    - name: Restore pristine Homebrew
      id: cache_restore
      if: inputs.restore == 'true' && steps.cache_lookup.outputs.cache-hit == 'true'
      uses: actions/cache/restore@v4
      with:
        path: |
          /opt/homebrew/bin
          /opt/homebrew/etc
        key: brew-pristine-${{ inputs.os }}-${{ github.ref_name }}-${{ steps.brew.outputs.version }}-test-multi2
    - name: Make Homebrew pristine
      if: steps.cache_lookup.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail

        formulae=()
        while IFS= read -r f; do
          formulae+=("$f")
        done < <(brew list --formula)
        if [ "${#formulae[@]}" -gt 0 ]; then
          brew uninstall --formula --force "${formulae[@]}"
        fi

        casks=()
        while IFS= read -r c; do
          casks+=("$c")
        done < <(brew list --cask)
        if [ "${#casks[@]}" -gt 0 ]; then
          brew uninstall --cask --zap --force "${casks[@]}"
        fi

        taps=()
        while IFS= read -r t; do
          taps+=("$t")
        done < <(brew tap)
        if [ "${#taps[@]}" -gt 0 ]; then
          brew untap "${taps[@]}"
        fi
    - name: Save pristine Homebrew
      if: steps.cache_lookup.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          /opt/homebrew/bin
          /opt/homebrew/etc
        key: brew-pristine-${{ inputs.os }}-${{ github.ref_name }}-${{ steps.brew.outputs.version }}-test-multi2
